import { BusinessStatus, Role } from "@prisma/client";

// These will be generated by Prisma after `prisma generate` — defined locally until then
type PlatformRole = "SUPERADMIN" | "SUPPORT" | "FINANCE" | "ANALYST";
type PlatformUserStatus = "ACTIVE" | "INACTIVE";

declare global {
  namespace Express {
    interface Request {
      user?: {
        id: string;
        businessId: string;
        role: Role;
        business: {
          id: string;
          status: BusinessStatus;
          slug: string;
          name: string;
        };
      };
      platformUser?: {
        id: string;
        role: PlatformRole;
        status: PlatformUserStatus;
        name: string;
        email: string;
      };
      /** Set by customerAuthMiddleware — holds the CustomerAccount id */
      customerAccountId?: string;
    }
  }
}

export {};
