import type { Config } from "tailwindcss";

const token = (name: string) => `hsl(var(--${name}))`;
const scale = (name: string) => ({
  50: token(`${name}-50`),
  100: token(`${name}-100`),
  200: token(`${name}-200`),
  300: token(`${name}-300`),
  400: token(`${name}-400`),
  500: token(`${name}-500`),
  600: token(`${name}-600`),
  700: token(`${name}-700`),
  800: token(`${name}-800`),
  900: token(`${name}-900`),
  950: token(`${name}-950`),
});

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
    "./hooks/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
      },
      colors: {
        foreground: token("foreground"),
        neutral: scale("neutral"),
        slate: scale("slate"),
        stone: scale("stone"),
        gray: scale("gray"),
        zinc: {
          ...scale("zinc"),
          925: token("zinc-925"),
        },
        blue: scale("blue"),
        indigo: scale("indigo"),
        cyan: scale("cyan"),
        sky: scale("sky"),
        emerald: scale("emerald"),
        green: scale("green"),
        amber: scale("amber"),
        red: scale("red"),
        "on-primary-fixed": token("on-primary-fixed"),
        "inverse-on-surface": token("inverse-on-surface"),
        "primary-dim": token("primary-dim"),
        "on-error-container": token("on-error-container"),
        "on-secondary-container": token("on-secondary-container"),
        "surface-bright": token("surface-bright"),
        "on-primary-container": token("on-primary-container"),
        "on-secondary-fixed-variant": token("on-secondary-fixed-variant"),
        "tertiary-fixed": token("tertiary-fixed"),
        "primary-fixed-dim": token("primary-fixed-dim"),
        "background": token("background"),
        "surface-container-lowest": token("surface-container-lowest"),
        "on-tertiary": token("on-tertiary"),
        "on-surface": token("on-surface"),
        "surface-container-high": token("surface-container-high"),
        "outline-variant": token("outline-variant"),
        "on-secondary-fixed": token("on-secondary-fixed"),
        "error-dim": token("error-dim"),
        "on-tertiary-fixed-variant": token("on-tertiary-fixed-variant"),
        "surface-container-highest": token("surface-container-highest"),
        "on-primary": token("on-primary"),
        "on-background": token("on-background"),
        "error": token("error"),
        "primary-fixed": token("primary-fixed"),
        "secondary-fixed": token("secondary-fixed"),
        "inverse-surface": token("inverse-surface"),
        "on-tertiary-container": token("on-tertiary-container"),
        "surface": token("surface"),
        "tertiary-fixed-dim": token("tertiary-fixed-dim"),
        "surface-dim": token("surface-dim"),
        "surface-tint": token("surface-tint"),
        "secondary-fixed-dim": token("secondary-fixed-dim"),
        "primary-container": token("primary-container"),
        "outline": token("outline"),
        "tertiary-container": token("tertiary-container"),
        "secondary-dim": token("secondary-dim"),
        "on-secondary": token("on-secondary"),
        "inverse-primary": token("inverse-primary"),
        "surface-container-low": token("surface-container-low"),
        "surface-container": token("surface-container"),
        "on-tertiary-fixed": token("on-tertiary-fixed"),
        "secondary": token("secondary"),
        "error-container": token("error-container"),
        "primary": token("primary"),
        "tertiary-dim": token("tertiary-dim"),
        "on-primary-fixed-variant": token("on-primary-fixed-variant"),
        "secondary-container": token("secondary-container"),
        "on-surface-variant": token("on-surface-variant"),
        "tertiary": token("tertiary"),
        "surface-variant": token("surface-variant"),
        "on-error": token("on-error"),
      },
      keyframes: {
        "fade-in": {
          from: { opacity: "0", transform: "translateY(4px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        "slide-in": "slide-in 0.15s ease-out",
      },
    },
  },
  plugins: [],
};

export default config;
